import{a as L,S,i as d}from"./assets/vendor-BK_rxH-O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const w="23833623-5e498f716d92b70c670ceee0e",q="https://pixabay.com/api/";async function f(e,n=1,o=15){const a={key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:o};return(await L.get(q,{params:a})).data}const h=document.querySelector(".gallery");let v=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const n=e.map(({webformatURL:o,largeImageURL:a,tags:t,likes:r,views:l,comments:g,downloads:b})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${o}" alt="${t}" class="gallery-image" />
          <div class="image-info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${l}</p>
            <p><b>Comments:</b> ${g}</p>
            <p><b>Downloads:</b> ${b}</p>
          </div>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",n),v.refresh()}function E(){h.innerHTML=""}function B(){const e=document.querySelector(".loader");e.style.display="block"}function P(){const e=document.querySelector(".loader");e.style.display="none"}function M(){document.querySelector(".load-more").classList.remove("hidden")}function m(){document.querySelector(".load-more").classList.add("hidden")}function R(){document.querySelector(".loader-bottom").classList.remove("hidden")}function $(){document.querySelector(".loader-bottom").classList.add("hidden")}function O(){const e=document.querySelector(".gallery-item");if(e){const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}const x=document.querySelector(".form"),A=document.querySelector(".load-more");document.querySelector(".gallery");let c="",i=1;const s=15;let u=0;x.addEventListener("submit",H);A.addEventListener("click",I);async function H(e){e.preventDefault();const n=e.target.elements["search-text"].value.trim();if(!(n===c&&i>1)){if(c=n,i=1,E(),m(),!c){d.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}try{B();const o=await f(c,i,s);if(u=o.totalHits,o.hits.length===0){d.error({title:"Error",message:"No images found. Try another word!",position:"topRight"});return}y(o.hits),o.totalHits>s&&M(),(o.hits.length<s||i*s>=u)&&(m(),p())}catch(o){d.error({title:"Error",message:"Fetch error. Try again later.",position:"topRight"}),console.error(o)}finally{P()}}}async function I(){i+=1;try{R();const e=await f(c,i,s);y(e.hits),O(),i*s>=u&&(m(),p())}catch(e){d.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(e)}finally{$()}}function p(){i*s>=u&&u>s&&d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}
//# sourceMappingURL=index.js.map
