import{a as w,S as q,i as d}from"./assets/vendor-BK_rxH-O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E="23833623-5e498f716d92b70c670ceee0e",v="https://pixabay.com/api/";async function p(t,n=1,o=15){const s={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:o};return(await w.get(v,{params:s})).data}const h=document.querySelector(".gallery");let B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const n=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:l,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${o}" alt="${e}" class="gallery-image" />
          <div class="image-info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${l}</p>
            <p><b>Comments:</b> ${L}</p>
            <p><b>Downloads:</b> ${S}</p>
          </div>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",n),B.refresh()}function P(){h.innerHTML=""}function f(){document.querySelector(".loader").style.display="block"}function M(){document.querySelector(".loader").style.display="none"}function R(){document.querySelector(".load-more").classList.remove("hidden")}function m(){document.querySelector(".load-more").classList.add("hidden")}function y(){document.querySelector(".loader-bottom").style.display="block"}function $(){document.querySelector(".loader-bottom").style.display="none"}function O(){const t=document.querySelector(".gallery-item");if(t){const{height:n}=t.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}const x=document.querySelector(".form"),A=document.querySelector(".load-more");document.querySelector(".gallery");let c="",i=1;const a=15;let u=0;x.addEventListener("submit",H);A.addEventListener("click",I);async function H(t){t.preventDefault(),f();const n=t.target.elements["search-text"].value.trim();if(!(n===c&&i>1)){if(c=n,i=1,P(),m(),!c){d.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}try{f();const o=await p(c,i,a);if(u=o.totalHits,o.hits.length===0){d.error({title:"Error",message:"No images found. Try another word!",position:"topRight"});return}g(o.hits),o.totalHits>a&&R(),(o.hits.length<a||i*a>=u)&&(m(),b())}catch(o){d.error({title:"Error",message:"Fetch error. Try again later.",position:"topRight"}),console.error(o)}finally{M()}}}async function I(){i+=1,y();try{y();const t=await p(c,i,a);g(t.hits),O(),i*a>=u&&(m(),b())}catch(t){d.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(t)}finally{$()}}function b(){i*a>=u&&u>a&&d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}
//# sourceMappingURL=index.js.map
