import{a as w,S as q,i as d}from"./assets/vendor-BK_rxH-O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const x="23833623-5e498f716d92b70c670ceee0e",B="https://pixabay.com/api/";async function m(e,n=1,o=15){const s={key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:o};return(await w.get(B,{params:s})).data}const p=document.querySelector(".gallery");let E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(e){const n=e.map(({webformatURL:o,largeImageURL:s,tags:t,likes:r,views:l,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${o}" alt="${t}" class="gallery-image" />
          <div class="image-info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${l}</p>
            <p><b>Comments:</b> ${L}</p>
            <p><b>Downloads:</b> ${S}</p>
          </div>
        </a>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",n),E.refresh()}function M(){p.innerHTML=""}function f(){document.querySelector(".loader").style.display="block"}function v(){document.querySelector(".loader").style.display="none"}function h(){const e=document.querySelector(".load-more");e&&(e.style.display="block")}function y(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}function P(){document.querySelector(".loader-bottom").style.display="block"}function T(){document.querySelector(".loader-bottom").style.display="none"}function R(){const e=document.querySelector(".loading-text");e&&(e.style.display="block")}function $(){const e=document.querySelector(".loading-text");e&&(e.style.display="none")}function O(){const e=document.querySelector(".gallery-item");if(e){const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}const A=document.querySelector(".form"),H=document.querySelector(".load-more");document.querySelector(".gallery");let c="",i=1;const a=15;let u=0;A.addEventListener("submit",I);H.addEventListener("click",_);async function I(e){e.preventDefault(),f();const n=e.target.elements["search-text"].value.trim();if(!(n===c&&i>1)){if(c=n,i=1,M(),y(),!c){d.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}try{f();const o=await m(c,i,a);if(u=o.totalHits,o.hits.length===0){d.error({title:"Error",message:"No images found. Try another word!",position:"topRight"});return}g(o.hits),o.totalHits>a&&h(),(o.hits.length<a||i*a>=u)&&(y(),b())}catch(o){d.error({title:"Error",message:"Fetch error. Try again later.",position:"topRight"}),console.error(o)}finally{v()}}}async function _(){i+=1;try{P(),R(),y();const e=await m(c,i,a);g(e.hits),O(),i*a>=u?b():h()}catch(e){d.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(e)}finally{T(),$()}}function b(){i*a>=u&&u>a&&d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}
//# sourceMappingURL=index.js.map
